import SwiftUI

enum WorkspaceAccessibilityAction: String, CaseIterable, Hashable {
    case refreshWorkspace = "workspace.refresh"
    case quickOpen = "workspace.quick-open"
    case newTeam = "workspace.new-team"
    case showNavigator = "navigator.show"
    case hideNavigator = "navigator.hide"
    case searchSessions = "navigator.search"
    case newSession = "navigator.new-session"
    case filterSessions = "navigator.filter"
    case projectActions = "navigator.project-actions"
    case addContext = "composer.add-context"
    case send = "composer.send"
    case stopRun = "composer.stop-run"
    case findAndReplace = "editor.find-and-replace"
    case save = "editor.save"
    case newTerminal = "terminal.new"
    case splitRight = "terminal.split-right"
    case splitDown = "terminal.split-down"
    case moveGroupLeft = "terminal.move-group-left"
    case moveGroupRight = "terminal.move-group-right"
    case showTerminal = "terminal.show"
    case hideTerminal = "terminal.hide"
    case showInspector = "explorer.show"
    case hideInspector = "explorer.hide"
    case refreshFiles = "explorer.refresh-files"
    case fileVisibility = "explorer.file-visibility"
    case newFileOrFolder = "explorer.new-entry"
    case previousRevision = "revision.previous"
    case nextRevision = "revision.next"
    case scrollLatestOutput = "transcript.scroll-latest"
    case sessionActions = "session.actions"
    case copyResponse = "transcript.copy-response"
    case contextUsage = "session.context-usage"
    case refreshChanges = "explorer.refresh-changes"
    case commitChanges = "explorer.commit"
    case toggleHiddenFiles = "explorer.toggle-hidden-files"
    case copyError = "workspace.copy-error"
    case dismissError = "workspace.dismiss-error"
    case teamReconfigure = "team.reconfigure"

    var label: LocalizedStringResource {
        switch self {
        case .refreshWorkspace: "Refresh Workspace"
        case .quickOpen: "Quick Open"
        case .newTeam: "New Team"
        case .showNavigator: "Show Navigator"
        case .hideNavigator: "Hide Navigator"
        case .searchSessions: "Search Sessions"
        case .newSession: "New Session"
        case .filterSessions: "Filter Sessions"
        case .projectActions: "Project Actions"
        case .addContext: "Add Context"
        case .send: "Send"
        case .stopRun: "Stop Run"
        case .findAndReplace: "Find and Replace"
        case .save: "Save"
        case .newTerminal: "New Terminal"
        case .splitRight: "Split Right"
        case .splitDown: "Split Down"
        case .moveGroupLeft: "Move Terminal Group Left"
        case .moveGroupRight: "Move Terminal Group Right"
        case .showTerminal: "Show Terminal Panel"
        case .hideTerminal: "Hide Terminal Panel"
        case .showInspector: "Show Inspector"
        case .hideInspector: "Hide Inspector"
        case .refreshFiles: "Refresh Files"
        case .fileVisibility: "File Visibility"
        case .newFileOrFolder: "New File or Folder"
        case .previousRevision: "Previous Revision"
        case .nextRevision: "Next Revision"
        case .scrollLatestOutput: "Scroll to Latest Output"
        case .sessionActions: "Session Actions"
        case .copyResponse: "Copy Response"
        case .contextUsage: "Context Usage"
        case .refreshChanges: "Refresh Changes"
        case .commitChanges: "Commit"
        case .toggleHiddenFiles: "Show hidden files"
        case .copyError: "Copy Error"
        case .dismissError: "Dismiss"
        case .teamReconfigure: "Reconfigure Team"
        }
    }
}

extension View {
    func workspaceAccessibility(_ action: WorkspaceAccessibilityAction) -> some View {
        accessibilityLabel(Text(action.label))
            .accessibilityIdentifier(action.rawValue)
    }
}
